PDIST_METRIC_OPTIONS = [
    "cityblock",
    "euclidean",
    "cosine",
    "braycurtis",
    "canberra",
    "chebyshev",
    "correlation",
    "dice",
    "hamming",
    "jaccard",
    "jensenshannon",
    "kulczynski1",
    "mahalanobis",
    "matching",
    "minkowski",
    "rogerstanimoto",
    "russellrao",
    "seuclidean",
    "sokalmichener",
    "sokalsneath",
    "sqeuclidean",
    "yule",
]

LINKAGE_METHOD_OPTIONS = [
    "complete",
    "average",
    "single",
    "weighted",
    "centroid",
    "median",
    "ward",
]
