PLOTLY_MAP_PROJECTION_TYPES = [
    "robinson",
    "orthographic",
    "kavrayskiy7",
    "winkel tripel",
    "equirectangular",
    "mercator",
    "natural earth",
    "miller",
    "eckert4",
    "azimuthal equal area",
    "azimuthal equidistant",
    "conic equal area",
    "conic conformal",
    "conic equidistant",
    "gnomonic",
    "stereographic",
    "mollweide",
    "hammer",
    "transverse mercator",
    "albers usa",
    "aitoff",
    "sinusoidal",
]
